# Generated by Django 5.2.8 on 2025-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_options_alter_venta_options_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente_libre',
            field=models.CharField(blank=True, help_text='Para ventas sin cliente registrado', max_length=150, verbose_name='Nombre cliente (libre)'),
        ),
    ]
