# Generated by Django 5.2.8 on 2025-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(help_text='RUT con guion, ej: 12.345.678-9', max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('tiene_credito', models.BooleanField(default=False)),
                ('cupo_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Cupo máximo de crédito del cliente', max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Deuda actual del cliente (monto pendiente)', max_digits=12)),
                ('es_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
