# Generated by Django 5.2.8 on 2025-11-23 04:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.CreateModel(
            name='MovimientoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra a crédito'), ('ABONO', 'Abono'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_despues', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_credito', to='clientes.cliente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_credito', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de crédito',
                'verbose_name_plural': 'Movimientos de crédito',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
